import type { Project, Experience, Education, SkillCategory, Certification, Stat } from '@/types';

export const personalInfo = {
  name: 'Muhammad Talha',
  title: 'Flutter / Mobile Application Developer',
  email: 'talha.cusit.pk@gmail.com',
  phone: '(+92) 302-5232179',
  location: 'Peshawar, Pakistan',
  linkedin: 'https://www.linkedin.com/in/muhammad-talha-42b1ab315/',
  github: 'https://github.com/Talha162',
  summary: 'Flutter / Mobile Application Developer with 3+ years of experience building cross-platform Android and iOS applications. Strong expertise in Flutter, Firebase, Supabase, REST and GraphQL APIs, scalable mobile architecture, and real-time, offline-first, and role-based access systems. Experienced in Google Maps integration, payment workflows, native SDKs, and AI-powered features using OpenAI and Gemini APIs.',
};

export const stats: Stat[] = [
  { value: '3', label: 'Years Experience', suffix: '+' },
  { value: '22', label: 'Projects Completed', suffix: '+' },
  { value: '8', label: 'Apps Published', suffix: '+' },
  { value: '2', label: 'Companies Worked', suffix: '' },
];

export const skillCategories: SkillCategory[] = [
  {
    id: 'languages',
    title: 'Languages',
    icon: 'Code',
    skills: ['Dart', 'JavaScript', 'Python', 'C++', 'C#'],
  },
  {
    id: 'mobile',
    title: 'Mobile Development',
    icon: 'Smartphone',
    skills: ['Flutter', 'Clean Architecture', 'MVVM', 'MVC', 'Feature-First Architecture', 'Layered Architecture', 'Play Store / App Store Deployment'],
  },
  {
    id: 'state',
    title: 'State Management',
    icon: 'Layers',
    skills: ['Bloc', 'Riverpod', 'GetX', 'Provider'],
  },
  {
    id: 'firebase',
    title: 'Firebase & Supabase',
    icon: 'Cloud',
    skills: ['Firebase Auth', 'Firestore', 'Realtime Database', 'Storage', 'ML Kit', 'Cloud Functions', 'FCM', 'Firebase Analytics', 'Supabase Auth', 'PostgreSQL', 'Edge Functions', 'Row-Level Security (RLS)'],
  },
  {
    id: 'backend',
    title: 'Backend & APIs',
    icon: 'Server',
    skills: ['REST APIs', 'GraphQL APIs', 'FastAPI', 'Backend Integration'],
  },
  {
    id: 'features',
    title: 'Features & Integrations',
    icon: 'Puzzle',
    skills: ['Google Maps Integration', 'Native SDK Integration', 'Stripe Integration', 'Easypaisa Integration', 'JazzCash Integration', 'OpenAI API Integration', 'Gemini API Integration', 'Push Notifications', 'Chat', 'PDF Annotation', 'Offline-First Workflows'],
  },
  {
    id: 'tools',
    title: 'Tools & CI/CD',
    icon: 'Wrench',
    skills: ['Git', 'GitHub', 'GitHub Actions (CI/CD)', 'Codemagic', 'Bitrise', 'Fastlane', 'Postman', 'Swagger', 'Android Studio', 'VS Code'],
  },
  {
    id: 'deployment',
    title: 'Deployment',
    icon: 'Upload',
    skills: ['Google Play Console', 'App Store Connect', 'TestFlight'],
  },
];

export const projects: Project[] = [
  // ── Professional Projects ──────────────────────────────────────────────────
  {
    id: 'manifesto',
    title: 'Manifesto MD',
    description: 'Clinical reference and decision support app built for healthcare professionals. Features Firebase Auth, Firestore, Storage, and push notifications. Integrated AI-assisted diagnostic summaries and subscription workflows with RevenueCat. Managed full release cycle through Google Play Console, TestFlight, and App Store Connect.',
    tech: ['Flutter', 'Firebase', 'RevenueCat', 'AI Diagnostics', 'Push Notifications'],
    period: 'Nov 2025 - Present',
    company: 'Infinity Softwares',
    image: '/images/project-manifesto.png',
    links: { store: 'https://play.google.com' },
  },
  {
    id: 'chassis',
    title: 'Chassis Doctor',
    description: 'Motorsport setup diagnostics app that helps drivers and engineers analyse chassis behaviour. Built on Supabase with Gemini AI-powered setup recommendations and PDF report generation. Bundled with a structured setup learning hub of courses and TestFlight-based testing cycles.',
    tech: ['Flutter', 'Supabase', 'Gemini AI', 'PDF Reports', 'Learning Hub'],
    period: 'Oct 2025 - Present',
    company: 'Infinity Softwares',
    image: '/images/project-chassis.png',
    figmaUrl: 'https://www.figma.com/design/yV6nTZizB8HmBqFA7g05HI/Motorsport?node-id=0-1&p=f&t=Tc0YSu0BilCdPCFn-0',
  },
  {
    id: 'docusite',
    title: 'DocuSite',
    description: 'Cloud-synced field documentation system for construction teams, built around the native PDFTron SDK for PDF annotation, markup, and structured report generation. Uses GetX state management with role-based access, push notifications, and TestFlight distribution for iOS.',
    tech: ['Flutter', 'GetX', 'PDFTron SDK', 'Cloud Sync', 'Push Notifications'],
    period: 'Sep 2025 - Dec 2025',
    company: 'Infinity Softwares',
    image: '/images/project-docusite.png',
    figmaUrl: 'https://www.figma.com/design/wClnvm5cCURaJeIMNQnWPG/DocuSite?node-id=1-3&p=f&t=eTYQ2ni1JkAzAyvr-0',
  },
  {
    id: 'committee',
    title: 'Committee App',
    description: 'Monthly savings committee management system with fully separated admin and member workflows. Admins create committees, assign payout orders, and track payments via Stripe and Firebase Cloud Functions. Members receive real-time push notifications for payment reminders and payout confirmations.',
    tech: ['Flutter', 'Firebase', 'Stripe', 'Cloud Functions', 'Push Notifications'],
    period: 'Jun 2024 - Jul 2025',
    company: 'Nexum Technologies',
    image: '/images/project-committee.png',
    images: [
      '/images/project-committee.png',
      '/images/projects/committee/splash.png',
      '/images/projects/committee/login.png',
      '/images/projects/committee/signup.png',
      '/images/projects/committee/home.png',
      '/images/projects/committee/admin_auth.png',
      '/images/projects/committee/admin_committees_screen.png',
      '/images/projects/committee/admin_creating_committee.png',
      '/images/projects/committee/admin_committees_details.png',
      '/images/projects/committee/admin_selecting members_for_payout_order.png',
      '/images/projects/committee/committee_details page.png',
      '/images/projects/committee/payment_screen.png',
      '/images/projects/committee/notification_screen.png',
      '/images/projects/committee/notification_setup.png',
      '/images/projects/committee/menu_widget.png',
      '/images/projects/committee/profile1.png',
      '/images/projects/committee/profile2.png',
      '/images/projects/committee/about_us.png',
    ],
  },
  {
    id: 'cricket',
    title: 'Ball-by-Ball Cricket Scoring',
    description: 'Real-time cricket scoring app supporting full match and tournament management. Built with Flutter, Firebase, and GetX following MVC architecture. Features live ball-by-ball scoring, scorecard views, player and team stats, group chat, push notifications, and an AI chatbot for cricket rules — developed as a final year project.',
    tech: ['Flutter', 'Firebase', 'GetX', 'MVC', 'AI Chatbot', 'Real-Time'],
    period: 'Aug 2024 - Jul 2025',
    image: '/images/project-cricket.png',
    images: [
      '/images/project-cricket.png',
      '/images/projects/cricket/splash.png',
      '/images/projects/cricket/login.png',
      '/images/projects/cricket/home.png',
      '/images/projects/cricket/matches page.png',
      '/images/projects/cricket/ongoing match 2.png',
      '/images/projects/cricket/completed match scorecard.png',
      '/images/projects/cricket/tournament batting performers.png',
      '/images/projects/cricket/my tournaments page.png',
      '/images/projects/cricket/chatbot.png',
      '/images/projects/cricket/profile.png',
    ],
  },
  {
    id: 'afghflavor',
    title: 'AfghanFlavor',
    description: 'Full-featured food delivery platform with real-time order tracking via Google Maps. Implements separate customer, rider, and restaurant-facing flows using Firebase and MVC architecture. Customers browse restaurants, place orders, and track delivery live; riders receive optimised routes; restaurants manage menus and incoming orders.',
    tech: ['Flutter', 'Firebase', 'Google Maps', 'MVC', 'Real-Time Tracking'],
    period: 'Mar 2023 - Sep 2024',
    company: 'Nexum Technologies',
    image: '/images/project-afghflavor.png',
    images: [
      '/images/project-afghflavor.png',
      '/images/projects/afghflavor/unnamed.webp',
      '/images/projects/afghflavor/unnamed (1).webp',
      '/images/projects/afghflavor/unnamed (2).webp',
      '/images/projects/afghflavor/unnamed (3).webp',
      '/images/projects/afghflavor/unnamed (4).webp',
      '/images/projects/afghflavor/unnamed (5).webp',
      '/images/projects/afghflavor/unnamed (6).webp',
      '/images/projects/afghflavor/unnamed (7).webp',
      '/images/projects/afghflavor/unnamed (8).webp',
      '/images/projects/afghflavor/unnamed (9).webp',
    ],
    links: { store: 'https://play.google.com' },
  },
  {
    id: 'durshalta',
    title: 'Durshalta',
    description: 'Multi-vendor food and service delivery app published on both iOS and Android. Built with Firebase, MVC, and Google Maps for live location sharing between customers and riders. Features dual customer/rider interfaces, real-time order management, push notifications, and photo-based delivery verification.',
    tech: ['Flutter', 'Firebase', 'Google Maps', 'MVC', 'iOS & Android'],
    period: 'Mar 2023 - Sep 2024',
    company: 'Nexum Technologies',
    image: '/images/project-durshalta.png',
    images: [
      '/images/project-durshalta.png',
      '/images/projects/durshalta/300x650bb.webp',
      '/images/projects/durshalta/300x650bb (1).webp',
      '/images/projects/durshalta/300x650bb (2).webp',
      '/images/projects/durshalta/300x650bb (3).webp',
      '/images/projects/durshalta/300x650bb (4).webp',
      '/images/projects/durshalta/300x650bb (5).webp',
      '/images/projects/durshalta/300x650bb (6).webp',
    ],
    links: { store: 'https://apps.apple.com' },
  },
  {
    id: 'amz',
    title: 'AMZ Language Learning',
    description: 'Structured language learning app with lesson-based content, video lessons, and interactive quizzes. Integrates REST APIs for dynamic content delivery and tracks learner progress. Clean, intuitive UI designed to keep learners engaged through a progressive curriculum.',
    tech: ['Flutter', 'REST APIs', 'Video Lessons', 'Quiz Engine'],
    period: 'May 2025 - Jul 2025',
    company: 'Nexum Technologies',
    image: '/images/project-amz.png',
    figmaUrl: 'https://www.figma.com/design/6ty8ERmhAsDaYz2ir4tpRB/AMZ-App?node-id=0-1&p=f&t=e3kK9rDaB5fMPryL-0',
  },
  {
    id: 'vantage',
    title: 'VANE',
    description: 'AI-powered social media content creation and scheduling SaaS that coordinates multi-platform posts from a single content calendar. Includes OTP-based auth, post analytics, and a 15-screen MVP scope built with Riverpod and GoRouter on a Feature-First architecture.',
    tech: ['Flutter', 'Riverpod', 'GoRouter', 'Feature-First', 'REST APIs'],
    period: 'Feb 2025 - Apr 2025',
    image: '/images/project-vantage.png',
  },
  {
    id: 'kinvo',
    title: 'Kinvo',
    description: 'Date-and-discover app with card-based swipe discovery, real-time chat, video calls, and selectable discovery modes. Built across 31 screens on a Feature-First architecture with Riverpod state management.',
    tech: ['Flutter', 'Riverpod', 'Feature-First', 'Real-Time Chat', 'Video Calls'],
    period: 'Oct 2024 - Feb 2025',
    image: '/images/project-kinvo.png',
  },
  {
    id: 'makeithappen',
    title: 'Make It Happen',
    description: 'Mentorship and event platform spanning 47 screens with multi-step onboarding, event discovery and booking via payment webview, mentorship session scheduling, and lesson-based learning paths. Released on both iOS and Android with REST-backed content and Lottie-driven UI.',
    tech: ['Flutter', 'GetX', 'REST APIs', 'Lottie', 'Payment Webview'],
    period: 'Aug 2024 - Jan 2025',
    image: '/images/project-makeithappen.png',
  },

  // ── Additional Projects ────────────────────────────────────────────────────
  {
    id: 'seshbuilder',
    title: 'Sesh Builder',
    description: 'Sports session and match scheduling app that lets users host or join local matches. Players create profiles, browse nearby sessions, and manage their created and joined matches. Designed for casual sports communities looking to organise informal games quickly.',
    tech: ['Flutter', 'Firebase', 'GetX', 'Location Services'],
    period: '2023 - 2024',
    image: '/images/project-seshbuilder.png',
    images: [
      '/images/project-seshbuilder.png',
      '/images/projects/seshbuilder/splash.png',
      '/images/projects/seshbuilder/signin.png',
      '/images/projects/seshbuilder/signup.png',
      '/images/projects/seshbuilder/home.png',
      '/images/projects/seshbuilder/host match.png',
      '/images/projects/seshbuilder/join match.png',
      '/images/projects/seshbuilder/your created matches.png',
      '/images/projects/seshbuilder/your joined matches.png',
      '/images/projects/seshbuilder/profile.png',
    ],
    figmaUrl: 'https://www.figma.com/design/ylDjVuu9ynmopqg45aHdIn/Sports-App?node-id=0-1&p=f&t=5GYItniPg7q7x0Oh-0',
  },
  {
    id: 'asthma',
    title: 'Asthma Weather Alert App',
    description: 'Health utility app that monitors weather conditions and issues personalised asthma risk alerts. Integrates a weather API to display 6-day forecasts and correlates environmental factors (pollen, humidity, air quality) with asthma risk levels. Includes an AI chatbot for symptom guidance, profile management, and admin panel.',
    tech: ['Flutter', 'Firebase', 'Weather API', 'AI Chatbot', 'Push Notifications'],
    period: '2023 - 2024',
    image: '/images/project-asthma.png',
    images: [
      '/images/project-asthma.png',
      '/images/projects/asthma/splash.png',
      '/images/projects/asthma/login.png',
      '/images/projects/asthma/home.png',
      '/images/projects/asthma/6 days forcast.png',
      '/images/projects/asthma/weather report.png',
      '/images/projects/asthma/notifications.png',
      '/images/projects/asthma/chatboat.png',
      '/images/projects/asthma/profile.png',
      '/images/projects/asthma/admin.png',
    ],
  },
  {
    id: 'gamegrid',
    title: 'Game Grid',
    description: 'Gaming discovery app that lets users browse, explore, and review games across categories. Features detailed game pages with PC/console specs, player reviews, and statistical analysis. Users can search by genre, view community ratings, and maintain their personal game library.',
    tech: ['Flutter', 'REST APIs', 'Firebase', 'GetX'],
    period: '2023 - 2024',
    image: '/images/project-gamegrid.png',
    images: [
      '/images/project-gamegrid.png',
      '/images/projects/gamegrid/splash.png',
      '/images/projects/gamegrid/login.png',
      '/images/projects/gamegrid/signup.png',
      '/images/projects/gamegrid/home.png',
      '/images/projects/gamegrid/games in one category.png',
      '/images/projects/gamegrid/single game info.png',
      '/images/projects/gamegrid/PC specs.png',
      '/images/projects/gamegrid/player reviews.png',
      '/images/projects/gamegrid/statistical analysis.png',
      '/images/projects/gamegrid/menue.png',
      '/images/projects/gamegrid/fogot pass.png',
      '/images/projects/gamegrid/about us.png',
    ],
  },
  {
    id: 'dryneedling',
    title: 'Dry Needling Reference',
    description: 'Medical reference app designed for physiotherapists and dry needling practitioners. Provides a structured anatomical guide organised by body regions and muscles, with detailed muscle descriptions and dry needling point references. Includes an AI chatbot for clinical queries and secure login for practitioners.',
    tech: ['Flutter', 'Firebase', 'AI Chatbot', 'Medical Reference'],
    period: '2023 - 2024',
    image: '/images/project-dryneedling.png',
    images: [
      '/images/project-dryneedling.png',
      '/images/projects/dryneedling/login.png',
      '/images/projects/dryneedling/home.png',
      '/images/projects/dryneedling/regions.png',
      '/images/projects/dryneedling/muscles in a region.png',
      '/images/projects/dryneedling/muscle detail.png',
      '/images/projects/dryneedling/chatboat.png',
    ],
  },
  {
    id: 'onlynoodle',
    title: 'Only Noodle',
    description: 'UI prototype for a noodle-focused food ordering experience with a clean, appetising visual language. Customers browse a curated menu, customise orders, and move through a streamlined checkout flow, with Syncfusion charts visualising menu insights.',
    tech: ['Flutter', 'GetX', 'REST APIs', 'Syncfusion Charts'],
    period: '2023 - 2024',
    image: '/images/project-onlynoodle.png',
    figmaUrl: 'https://www.figma.com/design/jnEEnEKAxRzliUOOZqpLBg/Only-Noodle?node-id=1-3&p=f&t=6WqBudJJkEhMMZs7-0',
  },
  {
    id: 'passionport',
    title: 'Passionport',
    description: 'Social networking app connecting people through shared passions, featuring peer-to-peer video calls via the HMS SDK and real-time chat over Socket.io. Users build interest-based profiles, edit media in-app, and interact through activity feeds and direct messaging.',
    tech: ['Flutter', 'HMS SDK', 'Socket.io', 'Video Calls', 'Media Editing'],
    period: '2023 - 2024',
    image: '/images/project-passionport.png',
    figmaUrl: 'https://www.figma.com/design/7NqyGoXTfJlcNmzy1NBA3H/Social-App?node-id=56-2432&p=f&t=rSMNv4ynYwNpoQkD-0',
  },
  {
    id: 'ussoccer',
    title: 'USA Soccer League',
    description: 'Early-stage UI prototype for a USA soccer league management app covering team rosters, match scheduling, and standings. Built with Provider for lightweight state management and focused on screen-flow validation rather than backend integration.',
    tech: ['Flutter', 'Provider', 'UI Prototype', 'Sports Management'],
    period: '2023 - 2024',
    image: '/images/project-ussoccer.jpg',
    figmaUrl: 'https://www.figma.com/design/N3NFyQDYdLsmlgGNS4IgIB/edwardb-project?node-id=4-2&p=f&t=lPPpJPiRZimKeHx2-0',
  },
  {
    id: 'retroflyy',
    title: 'RetroFlyy',
    description: 'UI mockup for a retro-inspired travel discovery experience. Showcases destination browsing, curated travel packages, and a booking flow rendered from hardcoded data — designed primarily as a design-fidelity prototype.',
    tech: ['Flutter', 'GetX', 'Google Fonts', 'UI Prototype'],
    period: '2023 - 2024',
    image: '/images/project-retroflyy.png',
    figmaUrl: 'https://www.figma.com/design/ZCfLV3eragEeI2oPPryr3B/RetroFlyy?node-id=0-1&p=f&t=GSoo3akPkxg1CCVY-0',
  },
  {
    id: 'farmer',
    title: 'Greek Farmer Market',
    description: 'Dual-role marketplace connecting Greek consumers with local farm producers, supporting in-app browsing, ordering, and Stripe-powered checkout. Built with GetX and flutter_map for producer discovery, REST APIs for catalogue and orders, and get_storage for lightweight local persistence.',
    tech: ['Flutter', 'GetX', 'Stripe', 'flutter_map', 'REST APIs'],
    period: '2023 - 2024',
    image: '/images/project-farmer.png',
    figmaUrl: 'https://www.figma.com/design/OXedVCPQzCUEI0GN96DWAt/farmer?node-id=0-1&p=f&t=FDgzXZepIqJSHWIr-0',
  },
  {
    id: 'fleetmgmt',
    title: 'Fleet Management App',
    description: 'Vehicle fleet tracking and management solution for logistics companies with real-time GPS tracking, route optimisation, and trip history. Features on-device OCR for driver document verification via Firebase ML Kit and Google ML Kit, with role-based access for fleet managers, dispatchers, and drivers.',
    tech: ['Flutter', 'Firebase', 'Google Maps', 'ML Kit OCR', 'Role-Based Access'],
    period: '2023 - 2024',
    image: '/images/project-fleetmgmt.png',
    figmaUrl: 'https://www.figma.com/design/C9NgjBIwlOluV0tcPk0Ykf/Fleet-Management-App?node-id=0-1&p=f&t=Jbi7E0t9j7uVPyxK-0',
  },
  {
    id: 'educationalapp',
    title: 'Educational Platform',
    description: 'E-learning platform app with structured courses, video lessons, quizzes, and learner progress tracking. Students can enrol in courses, watch video content, complete module quizzes, and track their learning journey. Instructors can manage course content through an admin interface.',
    tech: ['Flutter', 'Firebase', 'REST APIs', 'Video Streaming', 'E-Learning'],
    period: '2023 - 2024',
    image: '/images/project-educationalapp.png',
    figmaUrl: 'https://www.figma.com/design/NyGcFld64xEas1DXHgNorA/Educational-App?node-id=0-1&p=f&t=2iiBJyr5TD6UBK6G-0',
  },
];

export const experiences: Experience[] = [
  {
    id: 'infinity',
    role: 'Senior Flutter Developer',
    company: 'Infinity Softwares Company',
    location: 'Islamabad',
    period: 'Sep 2025 - Present',
    type: 'Full-time',
    responsibilities: [
      'Build and maintain Flutter apps for Android and iOS using clean, scalable architecture.',
      'Integrate Firebase, Supabase, REST APIs, native SDKs, and backend services.',
      'Develop chat, notifications, maps, payments, PDF annotation, offline, and AI features.',
      'Collaborate with designers, backend engineers, and QA to deliver stable mobile products.',
    ],
  },
  {
    id: 'nextera',
    role: 'Flutter Developer',
    company: 'Nexum Technologies',
    location: 'Peshawar',
    period: 'Feb 2023 - Sep 2025',
    type: 'Full-time',
    responsibilities: [
      'Delivered cross-platform Flutter applications across food delivery, education, utility, and management domains.',
      'Integrated Firebase, REST APIs, authentication systems, cloud services, and real-time data features.',
      'Built payment, notification, location-based, and role-based workflows for production mobile apps.',
      'Improved app performance, UI consistency, and code maintainability through debugging and refactoring.',
    ],
  },
];

export const education: Education[] = [
  {
    id: 'msc',
    degree: 'Master of Science in Computer Science (MSCS)',
    institution: 'National University of Computer & Emerging Sciences (FAST-NUCES)',
    location: 'Islamabad',
    period: 'Present',
  },
  {
    id: 'bcs',
    degree: 'Bachelor of Computer Science',
    institution: 'City University of Science & IT',
    location: 'Peshawar',
    period: '2021 - 2025',
  },
];

export const certifications: Certification[] = [
  {
    id: 'meta',
    name: 'Meta Android Developer Professional Certificate',
    provider: 'Coursera',
    year: '2023',
  },
  {
    id: 'flutter-bootcamp',
    name: 'The Complete Flutter Development Bootcamp with Dart',
    provider: 'Udemy',
    year: '2023',
  },
  {
    id: 'flutter',
    name: 'Google Flutter Development Certification',
    provider: 'Google',
    year: '2023',
  },
  {
    id: 'python',
    name: 'Python for Data Science, AI & Development',
    provider: 'Coursera',
    year: '2022',
  },
  {
    id: 'web',
    name: 'HTML, CSS, and Javascript for Web Developers',
    provider: 'Coursera',
    year: '2022',
  },
];

export const publishedApps = [
  { name: 'AfghanFlavor', type: 'Food Delivery', stores: ['Google Play'] },
  { name: 'Durshalta', type: 'Multi-Vendor Delivery', stores: ['App Store'] },
  { name: 'Manifesto MD', type: 'Clinical Reference', stores: ['Google Play', 'App Store'] },
];
